name: Android Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 🏗 Setup EAS CLI
        run: npm install -g eas-cli

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build Android APK
        # Maine yahan force flag add kar diya hai taaki keystore apne aap ban jaye
        run: npx eas-cli build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
